### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by TecInfoGnali** [zemmyang/Habitica-GoogleTasksSync#6]
```
10:46:18	Notificação	Execução iniciada
10:46:18	Erro	
ReferenceError: scriptProperties is not defined
(anônimo)	@ GTasks_init.gs:2
```

**Comment by zemmyang** [comment]
are you sure you copy-pasted all the files? scriptProperties is defined in the first line of main.gs

**Comment by TecInfoGnali** [comment]
yes, but don't work 
![image](https://user-images.githubusercontent.com/98838346/211008862-3eb0259b-7a35-405b-860a-1e2f50dd8dab.png)

**Comment by RPA-Piza** [comment]
Hello! I had the same problem, @zemmyang , I think it's the method in which you read the property in the Gtasks_init.gs file, you're using scriptProperties.getProperty but I see from your comment you've asked  @TecInfoGnali to log using PropertiesService.getScriptProperties().getProperty(), I replaced one for the other and I got it over that hurdle

const gtasksOptionalArgs = {
    'maxResults': PropertiesService.getScriptProperties().getProperty("gtasks_maxresults"),
    'showHidden':true
};

This gets repated all over Habitica_init.gs too, so I did the old Find / Replace and got it working.

Another thing I noticed is in line 69 of Habitica_init.gs, you have a Logger.log(response) for the getTags() function, where it should be Logger.log(taglistResponse); 

Probably missed it because it's been a while since that's error'ed in your project.

Once that is accounted for, it ran on my end. 

On last thing to be careful with is making sure to have the API Url end in a "/", otherwise your Buildrequest function doesn't work:
![image](https://user-images.githubusercontent.com/53017565/214414913-793302f4-75f6-402c-bd0a-23a0865cd782.png)

Hope this helps you @TecInfoGnali !

**Comment by gabrielmoris** [comment]
Again same error.

**Comment by zemmyang** [comment]
@TecInfoGnali I had `const scriptProperties = PropertiesService.getScriptProperties();` in the first line of main.gs so that I don't have to keep calling `PropertiesService.getScriptProperties();` all over the place, and it worked on testing so I'm not sure what's going on.

Anyway, I merged your PR, tested it on my end and it seems to work.
